# Generated by Django 6.1.1 on 2026-09-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(help_text='Truckstop Name', max_length=255)),
                ('address', models.CharField(help_text='Physical Address', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='2-letter US State Code', max_length=10)),
                ('latitude', models.FloatField(help_text='Latitude in decimal degrees')),
                ('longitude', models.FloatField(help_text='Longitude in decimal degrees')),
                ('retail_price', models.DecimalField(decimal_places=4, help_text='Minimum retail price per gallon ($)', max_digits=8)),
                ('geocode_source', models.CharField(help_text='Source of coordinates', max_length=50)),
                ('precision', models.CharField(help_text='Precision classification', max_length=50)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'db_table': 'fuel_stations',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_lat_lon_idx')],
            },
        ),
    ]
