# Generated by Django 6.1.1 on 2026-09-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('latitude', models.FloatField(help_text='WGS84 latitude')),
                ('longitude', models.FloatField(help_text='WGS84 longitude')),
                ('display_name', models.CharField(help_text='Formatted address returned by geocoder', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Geocoding Cache Entry',
                'verbose_name_plural': 'Geocoding Cache Entries',
                'db_table': 'geocoding_cache',
            },
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('distance_miles', models.FloatField(help_text='Total driving distance in miles')),
                ('duration_seconds', models.FloatField(help_text='Total estimated driving duration in seconds')),
                ('geometry', models.JSONField(help_text='GeoJSON LineString geometry coordinates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route Cache Entry',
                'verbose_name_plural': 'Route Cache Entries',
                'db_table': 'route_cache',
            },
        ),
    ]
