# Generated by Django 6.1.1 on 2026-10-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0002_geocodingcache_routecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationMatchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Cache key: route_key|corridor_miles', max_length=255, unique=True)),
                ('matches', models.JSONField(help_text='List of candidate stations along route corridor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Station Match Cache Entry',
                'verbose_name_plural': 'Station Match Cache Entries',
                'db_table': 'station_match_cache',
            },
        ),
    ]
